"""C++ client emitter for the Picomesh msgpack frontend.

Self-contained except for the vendored cmp codec (ship cmp.{c,h}); compiles
with g++ -std=c++17. Typed method per model method."""

GEN_NOTE = "// AUTO-GENERATED by tools/msgpack-codegen — do not edit.\n"

_PARAM = {"int": "int64_t", "uint": "uint64_t", "float": "double", "str": "const std::string&"}
_WRITE = {
    "int": "cmp_write_integer(&w, (int64_t){n});",
    "uint": "cmp_write_uinteger(&w, (uint64_t){n});",
    "float": "cmp_write_decimal(&w, (double){n});",
    "str": "cmp_write_str(&w, {n}.c_str(), (uint32_t){n}.size());",
}
_RET = {"int": ("int64_t", "res_i64"), "uint": ("uint64_t", "res_u64"),
        "float": ("double", "res_f64"), "str": ("std::string", "res_str")}

_TEMPLATE = '''<<GEN_NOTE>>// Generated msgpack client for `<<MODULE>>`.
// Build with the vendored cmp codec, e.g.:
//   g++ -std=c++17 -I path/to/cmp your_app.cpp cmp.c
#pragma once

#include <cmp.h>

#include <cstdint>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

#include <arpa/inet.h>
#include <sys/socket.h>
#include <unistd.h>

namespace <<NS>> {

struct MsgpackError : std::runtime_error {
    std::string code;
    MsgpackError(const std::string& m, std::string c) : std::runtime_error(m), code(std::move(c)) {}
};

class Client {
public:
    explicit Client(std::string host = "127.0.0.1", int port = 7900)
        : host_(std::move(host)), port_(port) {}

<<METHODS>>
private:
    std::string host_;
    int port_;

    struct cur { uint8_t* data; size_t cap; size_t off; };
    static bool rd(cmp_ctx_t* c, void* d, size_t n) {
        cur* b = static_cast<cur*>(c->buf);
        if (n > b->cap || b->off > b->cap - n) return false;
        std::memcpy(d, b->data + b->off, n); b->off += n; return true;
    }
    static bool sk(cmp_ctx_t* c, size_t n) {
        cur* b = static_cast<cur*>(c->buf);
        if (n > b->cap || b->off > b->cap - n) return false;
        b->off += n; return true;
    }
    static size_t wr(cmp_ctx_t* c, const void* d, size_t n) {
        cur* b = static_cast<cur*>(c->buf);
        if (n > b->cap || b->off > b->cap - n) return 0;
        std::memcpy(b->data + b->off, d, n); b->off += n; return n;
    }
    static void writen(int fd, const void* p, size_t n) {
        const uint8_t* b = static_cast<const uint8_t*>(p); size_t o = 0;
        while (o < n) { ssize_t w = ::write(fd, b + o, n - o); if (w <= 0) throw MsgpackError("write failed", "io"); o += static_cast<size_t>(w); }
    }
    static void readn(int fd, void* p, size_t n) {
        uint8_t* b = static_cast<uint8_t*>(p); size_t o = 0;
        while (o < n) { ssize_t r = ::read(fd, b + o, n - o); if (r <= 0) throw MsgpackError("read failed", "io"); o += static_cast<size_t>(r); }
    }
    int dial() {
        int fd = ::socket(AF_INET, SOCK_STREAM, 0);
        if (fd < 0) throw MsgpackError("socket failed", "io");
        sockaddr_in a{}; a.sin_family = AF_INET; a.sin_port = htons(static_cast<uint16_t>(port_));
        if (::inet_pton(AF_INET, host_.c_str(), &a.sin_addr) != 1) { ::close(fd); throw MsgpackError("bad host", "io"); }
        if (::connect(fd, reinterpret_cast<sockaddr*>(&a), sizeof(a)) < 0) { ::close(fd); throw MsgpackError("connect failed", "io"); }
        return fd;
    }
    std::vector<uint8_t> call(const char* path, const uint8_t* args, size_t args_len) {
        std::vector<uint8_t> env(args_len + std::strlen(path) + 256);
        cur wb{env.data(), env.size(), 0};
        cmp_ctx_t w; cmp_init(&w, &wb, rd, sk, wr);
        cmp_write_map(&w, 6);
        cmp_write_str(&w, "v", 1); cmp_write_integer(&w, 1);
        cmp_write_str(&w, "op", 2); cmp_write_str(&w, "invoke", 6);
        cmp_write_str(&w, "path", 4); cmp_write_str(&w, path, static_cast<uint32_t>(std::strlen(path)));
        cmp_write_str(&w, "args", 4);
        std::memcpy(env.data() + wb.off, args, args_len); wb.off += args_len;
        cmp_write_str(&w, "kwargs", 6); cmp_write_map(&w, 0);
        cmp_write_str(&w, "headers", 7); cmp_write_map(&w, 0);
        env.resize(wb.off);

        int fd = dial();
        uint8_t lb[4]; uint32_t len = htonl(static_cast<uint32_t>(env.size())); std::memcpy(lb, &len, 4);
        writen(fd, lb, 4); writen(fd, env.data(), env.size());
        readn(fd, lb, 4); std::memcpy(&len, lb, 4); uint32_t n = ntohl(len);
        std::vector<uint8_t> resp(n); readn(fd, resp.data(), n); ::close(fd);

        cur rb{resp.data(), resp.size(), 0};
        cmp_ctx_t r; cmp_init(&r, &rb, rd, sk, wr);
        uint32_t top = 0; if (!cmp_read_map(&r, &top)) throw MsgpackError("bad response", "bad_envelope");
        bool ok = false; size_t roff = 0, rlen = 0; bool have = false;
        std::string emsg = "remote error", ecode = "error";
        for (uint32_t i = 0; i < top; ++i) {
            char k[32]; uint32_t kl = sizeof(k); if (!cmp_read_str(&r, k, &kl)) break;
            if (std::strcmp(k, "ok") == 0) { bool b = false; cmp_read_bool(&r, &b); ok = b; }
            else if (std::strcmp(k, "result") == 0) { roff = rb.off; cmp_skip_object_no_limit(&r); rlen = rb.off - roff; have = true; }
            else if (std::strcmp(k, "error") == 0) {
                uint32_t ec = 0;
                if (cmp_read_map(&r, &ec)) for (uint32_t j = 0; j < ec; ++j) {
                    char ek[32]; uint32_t ekl = sizeof(ek); if (!cmp_read_str(&r, ek, &ekl)) break;
                    if (std::strcmp(ek, "message") == 0) { char mb[256]; uint32_t ml = sizeof(mb); if (cmp_read_str(&r, mb, &ml)) emsg = mb; }
                    else if (std::strcmp(ek, "code") == 0) { char cb[64]; uint32_t cl = sizeof(cb); if (cmp_read_str(&r, cb, &cl)) ecode = cb; }
                    else cmp_skip_object_no_limit(&r);
                }
            } else cmp_skip_object_no_limit(&r);
        }
        if (!ok) throw MsgpackError(emsg, ecode);
        if (!have) return {};
        return std::vector<uint8_t>(resp.begin() + static_cast<long>(roff),
                                    resp.begin() + static_cast<long>(roff + rlen));
    }
    static int64_t res_i64(const std::vector<uint8_t>& v) {
        cur b{const_cast<uint8_t*>(v.data()), v.size(), 0}; cmp_ctx_t r; cmp_init(&r, &b, rd, sk, wr);
        int64_t x = 0; if (!cmp_read_integer(&r, &x)) throw MsgpackError("bad int result", "call_error"); return x;
    }
    static uint64_t res_u64(const std::vector<uint8_t>& v) {
        cur b{const_cast<uint8_t*>(v.data()), v.size(), 0}; cmp_ctx_t r; cmp_init(&r, &b, rd, sk, wr);
        uint64_t x = 0; if (!cmp_read_uinteger(&r, &x)) throw MsgpackError("bad uint result", "call_error"); return x;
    }
    static double res_f64(const std::vector<uint8_t>& v) {
        cur b{const_cast<uint8_t*>(v.data()), v.size(), 0}; cmp_ctx_t r; cmp_init(&r, &b, rd, sk, wr);
        double x = 0; if (!cmp_read_decimal(&r, &x)) throw MsgpackError("bad float result", "call_error"); return x;
    }
    static std::string res_str(const std::vector<uint8_t>& v) {
        cur b{const_cast<uint8_t*>(v.data()), v.size(), 0}; cmp_ctx_t r; cmp_init(&r, &b, rd, sk, wr);
        uint32_t sz = 0; if (!cmp_read_str_size(&r, &sz)) throw MsgpackError("bad str result", "call_error");
        if (b.off + sz > v.size()) throw MsgpackError("truncated str", "call_error");
        return std::string(reinterpret_cast<const char*>(v.data() + b.off), sz);
    }
};

} // namespace <<NS>>
'''


def emit(module: str, methods: list) -> tuple:
    ns = module.replace("-", "_") + "_client"
    parts = []
    for m in methods:
        params = ", ".join(f"{_PARAM.get(a['kind'], 'int64_t')} {a['name']}" for a in m["args"])
        writes = "\n".join("        " + _WRITE[a["kind"]].format(n=a["name"]) for a in m["args"])
        n = len(m["args"])
        if m["ret_kind"] == "void":
            parts.append(
                f"    void {m['slot']}({params}) {{\n"
                f"        uint8_t a[65536]; cur wb{{a, sizeof(a), 0}};\n"
                f"        cmp_ctx_t w; cmp_init(&w, &wb, rd, sk, wr);\n"
                f"        cmp_write_array(&w, {n});\n"
                f"{writes}\n"
                f'        call("{m["path"]}", a, wb.off);\n'
                f"    }}\n")
        else:
            rtype, reader = _RET.get(m["ret_kind"], ("std::vector<uint8_t>", "/*raw*/"))
            parts.append(
                f"    {rtype} {m['slot']}({params}) {{\n"
                f"        uint8_t a[65536]; cur wb{{a, sizeof(a), 0}};\n"
                f"        cmp_ctx_t w; cmp_init(&w, &wb, rd, sk, wr);\n"
                f"        cmp_write_array(&w, {n});\n"
                f"{writes}\n"
                f'        return {reader}(call("{m["path"]}", a, wb.off));\n'
                f"    }}\n")
    text = (_TEMPLATE
            .replace("<<GEN_NOTE>>", GEN_NOTE)
            .replace("<<MODULE>>", module)
            .replace("<<NS>>", ns)
            .replace("<<METHODS>>", "\n".join(parts)))
    return text, f"{module}_client.hpp"
