"""Python client emitter for the Picomesh msgpack frontend.

Python's msgpack maps every value natively, so the client is thin: one typed
method per model method building the envelope. Verifiable against a running
frontend."""

GEN_NOTE = "# AUTO-GENERATED by tools/msgpack-codegen — do not edit.\n"

_TEMPLATE = '''<<GEN_NOTE>>"""Generated msgpack client for `<<MODULE>>`. Requires `msgpack` (pip)."""
import socket
import struct

import msgpack


class PicomeshError(Exception):
    def __init__(self, message, code=None):
        super().__init__(message)
        self.code = code


def _recv_exact(sock, n):
    buf = bytearray()
    while len(buf) < n:
        chunk = sock.recv(n - len(buf))
        if not chunk:
            raise ConnectionError("peer closed mid-frame")
        buf += chunk
    return bytes(buf)


class <<CLS>>:
    """Calls the picomesh `msgpack` frontend (Picomesh envelope, big-endian
    length-framed). One round-trip per call."""

    def __init__(self, host="127.0.0.1", port=7900, headers=None, timeout=10):
        self.host = host
        self.port = port
        self.headers = headers or {}
        self.timeout = timeout

    def _call(self, path, args):
        env = {"v": 1, "op": "invoke", "path": path,
               "args": list(args), "kwargs": {}, "headers": self.headers}
        payload = msgpack.packb(env, use_bin_type=True)
        with socket.create_connection((self.host, self.port), timeout=self.timeout) as sock:
            sock.sendall(struct.pack(">I", len(payload)) + payload)
            (n,) = struct.unpack(">I", _recv_exact(sock, 4))
            resp = msgpack.unpackb(_recv_exact(sock, n), raw=False)
        if not resp.get("ok"):
            err = resp.get("error", {})
            raise PicomeshError(err.get("message", "remote error"), err.get("code"))
        return resp.get("result")

<<BODY>>'''


def _class_name(module: str) -> str:
    return "".join(p.capitalize() for p in module.replace("-", "_").split("_")) + "Client"


def emit(module: str, methods: list) -> tuple:
    parts = []
    for m in methods:
        names = [a["name"] for a in m["args"]]
        sig = ", ".join(["self"] + names)
        arglist = "[" + ", ".join(names) + "]"
        parts.append(f"    def {m['slot']}({sig}):\n"
                     f"        return self._call({m['path']!r}, {arglist})\n")
    body = "\n".join(parts) if parts else "    pass\n"
    text = (_TEMPLATE
            .replace("<<GEN_NOTE>>", GEN_NOTE)
            .replace("<<MODULE>>", module)
            .replace("<<CLS>>", _class_name(module))
            .replace("<<BODY>>", body))
    return text, f"{module}_client.py"
