"""Rust client emitter for the Picomesh msgpack frontend.

Uses rmpv (dynamic Value). Typed method per model method."""

GEN_NOTE = "// AUTO-GENERATED by tools/msgpack-codegen — do not edit.\n"

_PARAM_TYPE = {"int": "i64", "uint": "u64", "float": "f64", "str": "&str"}
_RET = {
    "int": ("i64", 'r.as_i64().ok_or_else(|| "bad int result".to_string())'),
    "uint": ("u64", 'r.as_u64().ok_or_else(|| "bad uint result".to_string())'),
    "float": ("f64", 'r.as_f64().ok_or_else(|| "bad float result".to_string())'),
    "str": ("String", 'Ok(r.as_str().unwrap_or("").to_string())'),
}

_TEMPLATE = '''<<GEN_NOTE>>// Generated msgpack client for `<<MODULE>>`. Requires: rmpv = "1"
use std::io::{Read, Write};
use std::net::TcpStream;
use std::time::Duration;

use rmpv::Value;

pub struct Client {
    pub addr: String,
    pub headers: Vec<(Value, Value)>,
    pub timeout: Duration,
}

impl Client {
    pub fn new(addr: &str) -> Self {
        Client { addr: addr.to_string(), headers: Vec::new(), timeout: Duration::from_secs(10) }
    }

    fn call(&self, path: &str, args: Vec<Value>) -> Result<Value, String> {
        let env = Value::Map(vec![
            (Value::from("v"), Value::from(1)),
            (Value::from("op"), Value::from("invoke")),
            (Value::from("path"), Value::from(path)),
            (Value::from("args"), Value::Array(args)),
            (Value::from("kwargs"), Value::Map(vec![])),
            (Value::from("headers"), Value::Map(self.headers.clone())),
        ]);
        let mut buf = Vec::new();
        rmpv::encode::write_value(&mut buf, &env).map_err(|e| e.to_string())?;
        let mut stream = TcpStream::connect(&self.addr).map_err(|e| e.to_string())?;
        stream.set_read_timeout(Some(self.timeout)).ok();
        stream.write_all(&(buf.len() as u32).to_be_bytes()).map_err(|e| e.to_string())?;
        stream.write_all(&buf).map_err(|e| e.to_string())?;
        let mut lb = [0u8; 4];
        stream.read_exact(&mut lb).map_err(|e| e.to_string())?;
        let n = u32::from_be_bytes(lb) as usize;
        let mut body = vec![0u8; n];
        stream.read_exact(&mut body).map_err(|e| e.to_string())?;
        let resp = rmpv::decode::read_value(&mut &body[..]).map_err(|e| e.to_string())?;
        let (mut ok, mut result, mut emsg) = (false, Value::Nil, String::from("remote error"));
        if let Value::Map(pairs) = &resp {
            for (k, v) in pairs {
                match k.as_str() {
                    Some("ok") => ok = v.as_bool().unwrap_or(false),
                    Some("result") => result = v.clone(),
                    Some("error") => {
                        if let Value::Map(ep) = v {
                            for (ek, ev) in ep {
                                if ek.as_str() == Some("message") {
                                    emsg = ev.as_str().unwrap_or("remote error").to_string();
                                }
                            }
                        }
                    }
                    _ => {}
                }
            }
        }
        if !ok {
            return Err(emsg);
        }
        Ok(result)
    }

<<BODY>>}
'''


def emit(module: str, methods: list) -> tuple:
    parts = []
    for m in methods:
        params = ", ".join(f"{a['name']}: {_PARAM_TYPE.get(a['kind'], 'i64')}" for a in m["args"])
        argvals = ", ".join(f"Value::from({a['name']})" for a in m["args"])
        if m["ret_kind"] == "void":
            parts.append(
                f'    pub fn {m["slot"]}(&self, {params}) -> Result<(), String> {{\n'
                f'        self.call("{m["path"]}", vec![{argvals}])?;\n'
                f'        Ok(())\n'
                f'    }}\n')
        else:
            rtype, extract = _RET.get(m["ret_kind"], ("Value", "Ok(r)"))
            parts.append(
                f'    pub fn {m["slot"]}(&self, {params}) -> Result<{rtype}, String> {{\n'
                f'        let r = self.call("{m["path"]}", vec![{argvals}])?;\n'
                f'        {extract}\n'
                f'    }}\n')
    text = (_TEMPLATE
            .replace("<<GEN_NOTE>>", GEN_NOTE)
            .replace("<<MODULE>>", module)
            .replace("<<BODY>>", "\n".join(parts)))
    return text, f"{module}_client.rs"
