"""Go client emitter for the Picomesh msgpack frontend.

Uses github.com/vmihailenco/msgpack/v5. Typed method per model method."""

GEN_NOTE = "// AUTO-GENERATED by tools/msgpack-codegen — do not edit.\n"

_GO_TYPE = {"int": "int64", "uint": "uint64", "float": "float64", "str": "string"}

_TEMPLATE = '''<<GEN_NOTE>>// Generated msgpack client for `<<MODULE>>`.
// Requires: go get github.com/vmihailenco/msgpack/v5
package <<PKG>>

import (
	"encoding/binary"
	"fmt"
	"io"
	"net"
	"time"

	"github.com/vmihailenco/msgpack/v5"
)

// Client calls the picomesh msgpack frontend (Picomesh envelope, big-endian
// length-framed). One round-trip per call.
type Client struct {
	Addr    string
	Headers map[string]interface{}
	Timeout time.Duration
}

func New(addr string) *Client {
	return &Client{Addr: addr, Headers: map[string]interface{}{}, Timeout: 10 * time.Second}
}

type rpcError struct {
	Message string `msgpack:"message"`
	Code    string `msgpack:"code"`
}

func (c *Client) call(path string, args []interface{}, result interface{}) error {
	env := map[string]interface{}{
		"v": 1, "op": "invoke", "path": path,
		"args": args, "kwargs": map[string]interface{}{}, "headers": c.Headers,
	}
	payload, err := msgpack.Marshal(env)
	if err != nil {
		return err
	}
	conn, err := net.DialTimeout("tcp", c.Addr, c.Timeout)
	if err != nil {
		return err
	}
	defer conn.Close()
	_ = conn.SetDeadline(time.Now().Add(c.Timeout))
	var hdr [4]byte
	binary.BigEndian.PutUint32(hdr[:], uint32(len(payload)))
	if _, err := conn.Write(hdr[:]); err != nil {
		return err
	}
	if _, err := conn.Write(payload); err != nil {
		return err
	}
	if _, err := io.ReadFull(conn, hdr[:]); err != nil {
		return err
	}
	body := make([]byte, binary.BigEndian.Uint32(hdr[:]))
	if _, err := io.ReadFull(conn, body); err != nil {
		return err
	}
	var resp struct {
		Ok     bool               `msgpack:"ok"`
		Result msgpack.RawMessage `msgpack:"result"`
		Error  rpcError           `msgpack:"error"`
	}
	if err := msgpack.Unmarshal(body, &resp); err != nil {
		return err
	}
	if !resp.Ok {
		return fmt.Errorf("%s (%s)", resp.Error.Message, resp.Error.Code)
	}
	if result != nil && len(resp.Result) > 0 {
		return msgpack.Unmarshal(resp.Result, result)
	}
	return nil
}

<<BODY>>'''


def _pkg(module: str) -> str:
    return "".join(ch for ch in module.lower() if ch.isalnum()) + "client"


def _exported(slot: str) -> str:
    return "".join(p.capitalize() for p in slot.split("_"))


def emit(module: str, methods: list) -> tuple:
    parts = []
    for m in methods:
        params = ", ".join(f"{a['name']} {_GO_TYPE.get(a['kind'], 'int64')}" for a in m["args"])
        argvals = ", ".join(a["name"] for a in m["args"])
        name = _exported(m["slot"])
        rk = m["ret_kind"]
        if rk == "void":
            parts.append(
                f'func (c *Client) {name}({params}) error {{\n'
                f'\treturn c.call("{m["path"]}", []interface{{}}{{{argvals}}}, nil)\n'
                f'}}\n')
        else:
            gotype = _GO_TYPE.get(rk, "interface{}")
            parts.append(
                f'func (c *Client) {name}({params}) ({gotype}, error) {{\n'
                f'\tvar out {gotype}\n'
                f'\terr := c.call("{m["path"]}", []interface{{}}{{{argvals}}}, &out)\n'
                f'\treturn out, err\n'
                f'}}\n')
    text = (_TEMPLATE
            .replace("<<GEN_NOTE>>", GEN_NOTE)
            .replace("<<MODULE>>", module)
            .replace("<<PKG>>", _pkg(module))
            .replace("<<BODY>>", "\n".join(parts)))
    return text, f"{module}_client.go"
