"""Lua client emitter for the Picomesh msgpack frontend.

Uses lua-MessagePack + luasocket. Lua is dynamic, so the client is thin: one
method per model method building the envelope."""

GEN_NOTE = "-- AUTO-GENERATED by tools/msgpack-codegen — do not edit.\n"

_TEMPLATE = '''<<GEN_NOTE>>-- Generated msgpack client for `<<MODULE>>`.
-- Requires: luarocks install lua-MessagePack luasocket
local mp = require 'MessagePack'
local socket = require 'socket'

local Client = {}
Client.__index = Client

function Client.new(host, port, headers)
  return setmetatable({ host = host or '127.0.0.1', port = port or 7900, headers = headers or {} }, Client)
end

local function be32(n)
  return string.char(math.floor(n / 16777216) % 256, math.floor(n / 65536) % 256,
                     math.floor(n / 256) % 256, n % 256)
end

local function rd_be32(s)
  local a, b, c, d = s:byte(1, 4)
  return ((a * 256 + b) * 256 + c) * 256 + d
end

local function recv_exact(conn, n)
  local parts, got = {}, 0
  while got < n do
    local chunk, err = conn:receive(n - got)
    if not chunk then return nil, err end
    parts[#parts + 1] = chunk
    got = got + #chunk
  end
  return table.concat(parts)
end

function Client:call(path, args)
  -- mark `args` as an array so a single-element / empty arg list still encodes
  -- as a msgpack array rather than a map.
  local env = { v = 1, op = 'invoke', path = path,
                args = mp.Array(args), kwargs = {}, headers = self.headers }
  local payload = mp.pack(env)
  local conn = assert(socket.connect(self.host, self.port))
  conn:send(be32(#payload) .. payload)
  local hdr = assert(recv_exact(conn, 4))
  local body = assert(recv_exact(conn, rd_be32(hdr)))
  conn:close()
  local resp = mp.unpack(body)
  if not resp.ok then
    local e = resp.error or {}
    error((e.message or 'remote error') .. ' (' .. tostring(e.code) .. ')')
  end
  return resp.result
end

<<BODY>>
return Client
'''


def emit(module: str, methods: list) -> tuple:
    parts = []
    for m in methods:
        names = [a["name"] for a in m["args"]]
        sig = ", ".join(["self"] + names)
        arglist = "{ " + ", ".join(names) + " }"
        parts.append(f"function Client:{m['slot']}({sig})\n"
                     f"  return self:call('{m['path']}', {arglist})\nend\n")
    text = (_TEMPLATE
            .replace("<<GEN_NOTE>>", GEN_NOTE)
            .replace("<<MODULE>>", module)
            .replace("<<BODY>>", "\n".join(parts)))
    return text, f"{module}_client.lua"
